[font]
size = 8.0  # Normal is 8

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"


[general]
import = [
	"~/.config/alacritty/themes/themes/nord.toml"
]


[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
